verbose: false
instrumentation:
  root: .
  extensions:
    - .js
  include-all-sources: true
  excludes:
    - index.js
reporting:
  print: summary
  reports:
    - lcov
    - cobertura
    - clover
    - json
    - json-summary
  dir: ./coverage
  watermarks:
    statements: [50, 80]
    lines: [50, 80]
    functions: [50, 80]
    branches: [50, 80]
  report-config:
    clover: {file: clover.xml}
    cobertura: {file: cobertura-coverage.xml}
    json: {file: coverage-final.json}
    json-summary: {file: coverage-summary.json}